"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['scanner_tk.py']
DATA_FILES = ["MHG_METER.crfsuite", "corrections.csv"]
OPTIONS = {
    'argv_emulation': True,
    'packages': ['pycrfsuite'],
    'includes': [
        'pycrfsuite',
        'get_features',
        'only_four_stresses',
        'scan_text_new',
        'syllabipymhg3',
        'syllable2features',
        'yield_meter_tk']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
